from .models import Equipo, Nacionalidad

equipos_fifa18 = [
    {'nombre': 'Real Madrid', 'liga': 'La Liga'},
    {'nombre': 'FC Barcelona', 'liga': 'La Liga'},
    {'nombre': 'Atletico Madrid', 'liga': 'La Liga'},
    {'nombre': 'Valencia CF', 'liga': 'La Liga'},
    {'nombre': 'Sevilla FC', 'liga': 'La Liga'},
    {'nombre': 'Athletic Bilbao', 'liga': 'La Liga'},
    {'nombre': 'Villarreal CF', 'liga': 'La Liga'},
    {'nombre': 'Real Betis', 'liga': 'La Liga'},
    {'nombre': 'Real Sociedad', 'liga': 'La Liga'},
    {'nombre': 'Celta Vigo', 'liga': 'La Liga'},
    {'nombre': 'Eibar', 'liga': 'La Liga'},
    {'nombre': 'Deportivo Alaves', 'liga': 'La Liga'},
    {'nombre': 'Espanyol', 'liga': 'La Liga'},
    {'nombre': 'Getafe CF', 'liga': 'La Liga'},
    {'nombre': 'Girona FC', 'liga': 'La Liga'},
    {'nombre': 'Leganés', 'liga': 'La Liga'},
    {'nombre': 'Levante UD', 'liga': 'La Liga'},
    {'nombre': 'Malaga CF', 'liga': 'La Liga'},
    {'nombre': 'Las Palmas', 'liga': 'La Liga'},
    {'nombre': 'SD Eibar', 'liga': 'La Liga'},
    {'nombre': 'FC Midtjylland', 'liga': 'Alka Superliga'},
    {'nombre': 'Brondby IF', 'liga': 'Alka Superliga'},
    {'nombre': 'FC Copenhagen', 'liga': 'Alka Superliga'},
    {'nombre': 'FC Nordsjaelland', 'liga': 'Alka Superliga'},
    {'nombre': 'Aarhus GF', 'liga': 'Alka Superliga'},
    {'nombre': 'OB', 'liga': 'Alka Superliga'},
    {'nombre': 'SonderjyskE', 'liga': 'Alka Superliga'},
    {'nombre': 'Lyngby BK', 'liga': 'Alka Superliga'},
    {'nombre': 'AC Horsens', 'liga': 'Alka Superliga'},
    {'nombre': 'Silkeborg IF', 'liga': 'Alka Superliga'},
    {'nombre': 'Randers FC', 'liga': 'Alka Superliga'},
    {'nombre': 'Hobro IK', 'liga': 'Alka Superliga'},
    {'nombre': 'FC Helsingor', 'liga': 'Alka Superliga'},
    {'nombre': 'Aalborg BK', 'liga': 'Alka Superliga'},
    {'nombre': 'Esbjerg fB', 'liga': 'Alka Superliga'},
    {'nombre': 'Club Brugge', 'liga': 'Pro League'},
    {'nombre': 'Anderlecht', 'liga': 'Pro League'},
    {'nombre': 'KAA Gent', 'liga': 'Pro League'},
    {'nombre': 'Standard Liege', 'liga': 'Pro League'},
    {'nombre': 'Zulte Waregem', 'liga': 'Pro League'},
    {'nombre': 'KRC Genk', 'liga': 'Pro League'},
    {'nombre': 'Sporting Charleroi', 'liga': 'Pro League'},
    {'nombre': 'KV Oostende', 'liga': 'Pro League'},
    {'nombre': 'KV Mechelen', 'liga': 'Pro League'},
    {'nombre': 'Waasland-Beveren', 'liga': 'Pro League'},
    {'nombre': 'STVV', 'liga': 'Pro League'},
    {'nombre': 'Excel Mouscron', 'liga': 'Pro League'},
    {'nombre': 'Lokeren', 'liga': 'Pro League'},
    {'nombre': 'Antwerp', 'liga': 'Pro League'},
    {'nombre': 'Cercle Brugge', 'liga': 'Pro League'},
    {'nombre': 'Beerschot Wilrijk', 'liga': 'Pro League'},
    {'nombre': 'Flamengo', 'liga': 'Liga do Brasil'},
    {'nombre': 'Palmeiras', 'liga': 'Liga do Brasil'},
    {'nombre': 'Santos', 'liga': 'Liga do Brasil'},
    {'nombre': 'Corinthians', 'liga': 'Liga do Brasil'},
    {'nombre': 'Fluminense', 'liga': 'Liga do Brasil'},
    {'nombre': 'Vasco da Gama', 'liga': 'Liga do Brasil'},
    {'nombre': 'Botafogo', 'liga': 'Liga do Brasil'},
    {'nombre': 'Gremio', 'liga': 'Liga do Brasil'},
    {'nombre': 'Atletico Mineiro', 'liga': 'Liga do Brasil'},
    {'nombre': 'Bahia', 'liga': 'Liga do Brasil'},
    {'nombre': 'Atletico Paranaense', 'liga': 'Liga do Brasil'},
    {'nombre': 'Cruzeiro', 'liga': 'Liga do Brasil'},
    {'nombre': 'Sport Recife', 'liga': 'Liga do Brasil'},
    {'nombre': 'Coritiba', 'liga': 'Liga do Brasil'},
    {'nombre': 'Ponte Preta', 'liga': 'Liga do Brasil'},
    {'nombre': 'Avai', 'liga': 'Liga do Brasil'},
    {'nombre': 'Vitoria', 'liga': 'Liga do Brasil'},
    {'nombre': 'Chapecoense', 'liga': 'Liga do Brasil'},
    {'nombre': 'Atletico Goianiense', 'liga': 'Liga do Brasil'},
    {'nombre': 'Sao Paulo', 'liga': 'Liga do Brasil'},
    {'nombre': 'Ajax', 'liga': 'Eredivisie'},
    {'nombre': 'PSV Eindhoven', 'liga': 'Eredivisie'},
    {'nombre': 'Feyenoord', 'liga': 'Eredivisie'},
    {'nombre': 'AZ Alkmaar', 'liga': 'Eredivisie'},
    {'nombre': 'FC Utrecht', 'liga': 'Eredivisie'},
    {'nombre': 'Vitesse', 'liga': 'Eredivisie'},
    {'nombre': 'SC Heerenveen', 'liga': 'Eredivisie'},
    {'nombre': 'FC Twente', 'liga': 'Eredivisie'},
    {'nombre': 'Heracles Almelo', 'liga': 'Eredivisie'},
    {'nombre': 'PEC Zwolle', 'liga': 'Eredivisie'},
    {'nombre': 'Willem II', 'liga': 'Eredivisie'},
    {'nombre': 'FC Groningen', 'liga': 'Eredivisie'},
    {'nombre': 'NAC Breda', 'liga': 'Eredivisie'},
    {'nombre': 'ADO Den Haag', 'liga': 'Eredivisie'},
    {'nombre': 'Excelsior', 'liga': 'Eredivisie'},
    {'nombre': 'Roda JC Kerkrade', 'liga': 'Eredivisie'},
    {'nombre': 'Sparta Rotterdam', 'liga': 'Eredivisie'},
    {'nombre': 'VVV-Venlo', 'liga': 'Eredivisie'},
    {'nombre': 'FC Twente', 'liga': 'Eredivisie'},
    {'nombre': 'Roda JC Kerkrade', 'liga': 'Eredivisie'},
    {'nombre': 'Arsenal', 'liga': 'Premier League'},
    {'nombre': 'Chelsea', 'liga': 'Premier League'},
    {'nombre': 'Manchester United', 'liga': 'Premier League'},
    {'nombre': 'Manchester City', 'liga': 'Premier League'},
    {'nombre': 'Liverpool', 'liga': 'Premier League'},
    {'nombre': 'Tottenham Hotspur', 'liga': 'Premier League'},
    {'nombre': 'Everton', 'liga': 'Premier League'},
    {'nombre': 'Leicester City', 'liga': 'Premier League'},
    {'nombre': 'West Ham United', 'liga': 'Premier League'},
    {'nombre': 'Southampton', 'liga': 'Premier League'},
    {'nombre': 'Stoke City', 'liga': 'Premier League'},
    {'nombre': 'Crystal Palace', 'liga': 'Premier League'},
    {'nombre': 'Swansea City', 'liga': 'Premier League'},
    {'nombre': 'Burnley', 'liga': 'Premier League'},
    {'nombre': 'Watford', 'liga': 'Premier League'},
    {'nombre': 'Bournemouth', 'liga': 'Premier League'},
    {'nombre': 'West Bromwich Albion', 'liga': 'Premier League'},
    {'nombre': 'Huddersfield Town', 'liga': 'Premier League'},
    {'nombre': 'Brighton & Hove Albion', 'liga': 'Premier League'},
    {'nombre': 'Newcastle United', 'liga': 'Premier League'},
    {'nombre': 'Aston Villa', 'liga': 'EFL Championship'},
    {'nombre': 'Derby County', 'liga': 'EFL Championship'},
    {'nombre': 'Middlesbrough', 'liga': 'EFL Championship'},
    {'nombre': 'Leeds United', 'liga': 'EFL Championship'},
    {'nombre': 'Sheffield Wednesday', 'liga': 'EFL Championship'},
    {'nombre': 'Reading', 'liga': 'EFL Championship'},
    {'nombre': 'Fulham', 'liga': 'EFL Championship'},
    {'nombre': 'Norwich City', 'liga': 'EFL Championship'},
    {'nombre': 'Brentford', 'liga': 'EFL Championship'},
    {'nombre': 'Preston North End', 'liga': 'EFL Championship'},
    {'nombre': 'Ipswich Town', 'liga': 'EFL Championship'},
    {'nombre': 'Cardiff City', 'liga': 'EFL Championship'},
    {'nombre': 'Wolverhampton Wanderers', 'liga': 'EFL Championship'},
    {'nombre': 'Bristol City', 'liga': 'EFL Championship'},
    {'nombre': 'Barnsley', 'liga': 'EFL Championship'},
    {'nombre': 'Queens Park Rangers', 'liga': 'EFL Championship'},
    {'nombre': 'Nottingham Forest', 'liga': 'EFL Championship'},
    {'nombre': 'Hull City', 'liga': 'EFL Championship'},
    {'nombre': 'Sheffield United', 'liga': 'EFL Championship'},
    {'nombre': 'Bolton Wanderers', 'liga': 'EFL Championship'},
    {'nombre': 'Sheffield United', 'liga': 'League One'},
    {'nombre': 'Bolton Wanderers', 'liga': 'League One'},
    {'nombre': 'Bradford City', 'liga': 'League One'},
    {'nombre': 'Millwall', 'liga': 'League One'},
    {'nombre': 'Scunthorpe United', 'liga': 'League One'},
    {'nombre': 'Rochdale', 'liga': 'League One'},
    {'nombre': 'Fleetwood Town', 'liga': 'League One'},
    {'nombre': 'Bristol Rovers', 'liga': 'League One'},
    {'nombre': 'Peterborough United', 'liga': 'League One'},
    {'nombre': 'Southend United', 'liga': 'League One'},
    {'nombre': 'Oxford United', 'liga': 'League One'},
    {'nombre': 'Charlton Athletic', 'liga': 'League One'},
    {'nombre': 'MK Dons', 'liga': 'League One'},
    {'nombre': 'Walsall', 'liga': 'League One'},
    {'nombre': 'Northampton Town', 'liga': 'League One'},
    {'nombre': 'Chesterfield', 'liga': 'League One'},
    {'nombre': 'Bury', 'liga': 'League One'},
    {'nombre': 'Gillingham', 'liga': 'League One'},
    {'nombre': 'Port Vale', 'liga': 'League One'},
    {'nombre': 'Shrewsbury Town', 'liga': 'League One'},
    {'nombre': 'Portsmouth', 'liga': 'League Two'},
    {'nombre': 'Plymouth Argyle', 'liga': 'League Two'},
    {'nombre': 'Doncaster Rovers', 'liga': 'League Two'},
    {'nombre': 'Luton Town', 'liga': 'League Two'},
    {'nombre': 'Exeter City', 'liga': 'League Two'},
    {'nombre': 'Blackpool', 'liga': 'League Two'},
    {'nombre': 'Carlisle United', 'liga': 'League Two'},
    {'nombre': 'Colchester United', 'liga': 'League Two'},
    {'nombre': 'Wycombe Wanderers', 'liga': 'League Two'},
    {'nombre': 'Mansfield Town', 'liga': 'League Two'},
    {'nombre': 'Cambridge United', 'liga': 'League Two'},
    {'nombre': 'Stevenage', 'liga': 'League Two'},
    {'nombre': 'Yeovil Town', 'liga': 'League Two'},
    {'nombre': 'Crewe Alexandra', 'liga': 'League Two'},
    {'nombre': 'Crawley Town', 'liga': 'League Two'},
    {'nombre': 'Grimsby Town', 'liga': 'League Two'},
    {'nombre': 'Morecambe', 'liga': 'League Two'},
    {'nombre': 'Cheltenham Town', 'liga': 'League Two'},
    {'nombre': 'Accrington Stanley', 'liga': 'League Two'},
    {'nombre': 'Barnet', 'liga': 'League Two'},
    {'nombre': 'Notts County', 'liga': 'League Two'},
    {'nombre': 'Newport County', 'liga': 'League Two'},
    {'nombre': 'Hartlepool United', 'liga': 'League Two'},
    {'nombre': 'Leyton Orient', 'liga': 'League Two'},
    {'nombre': 'York City', 'liga': 'League Two'},
    {'nombre': 'Stevenage', 'liga': 'League Two'},
    {'nombre': 'Paris Saint-Germain', 'liga': 'Ligue 1'},
    {'nombre': 'AS Monaco', 'liga': 'Ligue 1'},
    {'nombre': 'Olympique de Marseille', 'liga': 'Ligue 1'},
    {'nombre': 'Olympique Lyonnais', 'liga': 'Ligue 1'},
    {'nombre': 'AS Saint-Étienne', 'liga': 'Ligue 1'},
    {'nombre': 'OGC Nice', 'liga': 'Ligue 1'},
    {'nombre': 'Girondins de Bordeaux', 'liga': 'Ligue 1'},
    {'nombre': 'FC Nantes', 'liga': 'Ligue 1'},
    {'nombre': 'Stade Rennais FC', 'liga': 'Ligue 1'},
    {'nombre': 'Toulouse FC', 'liga': 'Ligue 1'},
    {'nombre': 'Montpellier HSC', 'liga': 'Ligue 1'},
    {'nombre': 'LOSC Lille', 'liga': 'Ligue 1'},
    {'nombre': 'EA Guingamp', 'liga': 'Ligue 1'},
    {'nombre': 'FC Metz', 'liga': 'Ligue 1'},
    {'nombre': 'Angers SCO', 'liga': 'Ligue 1'},
    {'nombre': 'Dijon FCO', 'liga': 'Ligue 1'},
    {'nombre': 'SM Caen', 'liga': 'Ligue 1'},
    {'nombre': 'FC Lorient', 'liga': 'Ligue 1'},
    {'nombre': 'FC Sochaux-Montbéliard', 'liga': 'Ligue 1'},
    {'nombre': 'FC Girondins de Bordeaux', 'liga': 'Ligue 1'},
    {'nombre': 'En Avant de Guingamp', 'liga': 'Ligue 1'},
    {'nombre': 'Stade Malherbe Caen', 'liga': 'Ligue 1'},
    {'nombre': 'Stade Rennais Football Club', 'liga': 'Ligue 1'},
    {'nombre': 'FC Lorient Bretagne Sud', 'liga': 'Ligue 1'},
    {'nombre': 'RC Lens', 'liga': 'Ligue 2'},
    {'nombre': 'AC Ajaccio', 'liga': 'Ligue 2'},
    {'nombre': 'FC Sochaux-Montbéliard', 'liga': 'Ligue 2'},
    {'nombre': 'FC Lorient', 'liga': 'Ligue 2'},
    {'nombre': 'US Orléans', 'liga': 'Ligue 2'},
    {'nombre': 'Stade Brestois 29', 'liga': 'Ligue 2'},
    {'nombre': 'Valenciennes FC', 'liga': 'Ligue 2'},
    {'nombre': 'Clermont Foot', 'liga': 'Ligue 2'},
    {'nombre': 'Nîmes Olympique', 'liga': 'Ligue 2'},
    {'nombre': 'Chamois Niortais FC', 'liga': 'Ligue 2'},
    {'nombre': 'ESTAC Troyes', 'liga': 'Ligue 2'},
    {'nombre': 'AJ Auxerre', 'liga': 'Ligue 2'},
    {'nombre': 'Le Havre AC', 'liga': 'Ligue 2'},
    {'nombre': 'Paris FC', 'liga': 'Ligue 2'},
    {'nombre': 'FC Bourg-en-Bresse Péronnas', 'liga': 'Ligue 2'},
    {'nombre': 'Gazélec Ajaccio', 'liga': 'Ligue 2'},
    {'nombre': 'Tours FC', 'liga': 'Ligue 2'},
    {'nombre': 'Havre Athletic Club', 'liga': 'Ligue 2'},
    {'nombre': 'AJ Auxerre Bourgogne', 'liga': 'Ligue 2'},
    {'nombre': 'Paris Football Club', 'liga': 'Ligue 2'},
    {'nombre': 'Red Star FC', 'liga': 'Ligue 2'},
    {'nombre': 'Chamois Niortais Football Club', 'liga': 'Ligue 2'},
    {'nombre': 'Football Club de Lorient', 'liga': 'Ligue 2'},
    {'nombre': 'Tours Football Club', 'liga': 'Ligue 2'},
    {'nombre': 'Valenciennes Football Club', 'liga': 'Ligue 2'},
    {'nombre': 'FC Bayern Munich', 'liga': 'Bundesliga'},
    {'nombre': 'Borussia Dortmund', 'liga': 'Bundesliga'},
    {'nombre': 'RB Leipzig', 'liga': 'Bundesliga'},
    {'nombre': 'TSG 1899 Hoffenheim', 'liga': 'Bundesliga'},
    {'nombre': '1. FC Köln', 'liga': 'Bundesliga'},
    {'nombre': 'Hertha BSC', 'liga': 'Bundesliga'},
    {'nombre': 'SC Freiburg', 'liga': 'Bundesliga'},
    {'nombre': 'SV Werder Bremen', 'liga': 'Bundesliga'},
    {'nombre': 'Borussia Mönchengladbach', 'liga': 'Bundesliga'},
    {'nombre': 'FC Schalke 04', 'liga': 'Bundesliga'},
    {'nombre': 'Eintracht Frankfurt', 'liga': 'Bundesliga'},
    {'nombre': 'Bayer 04 Leverkusen', 'liga': 'Bundesliga'},
    {'nombre': 'FC Augsburg', 'liga': 'Bundesliga'},
    {'nombre': 'Hamburger SV', 'liga': 'Bundesliga'},
    {'nombre': '1. FSV Mainz 05', 'liga': 'Bundesliga'},
    {'nombre': 'VfL Wolfsburg', 'liga': 'Bundesliga'},
    {'nombre': 'Hannover 96', 'liga': 'Bundesliga'},
    {'nombre': 'Sport-Club Freiburg', 'liga': 'Bundesliga'},
    {'nombre': 'VfB Stuttgart', 'liga': 'Bundesliga'},
    {'nombre': 'FC Ingolstadt 04', 'liga': 'Bundesliga'},
    {'nombre': 'SV Darmstadt 98', 'liga': 'Bundesliga'},
    {'nombre': '1. FC Nürnberg', 'liga': 'Bundesliga 2'},
    {'nombre': 'MSV Duisburg', 'liga': 'Bundesliga 2'},
    {'nombre': 'Holstein Kiel', 'liga': 'Bundesliga 2'},
    {'nombre': 'Jahn Regensburg', 'liga': 'Bundesliga 2'},
    {'nombre': 'Fortuna Düsseldorf', 'liga': 'Bundesliga 2'},
    {'nombre': 'VfL Bochum', 'liga': 'Bundesliga 2'},
    {'nombre': 'SV Sandhausen', 'liga': 'Bundesliga 2'},
    {'nombre': 'Arminia Bielefeld', 'liga': 'Bundesliga 2'},
    {'nombre': '1. FC Union Berlin', 'liga': 'Bundesliga 2'},
    {'nombre': 'FC Ingolstadt 04', 'liga': 'Bundesliga 2'},
    {'nombre': 'SV Darmstadt 98', 'liga': 'Bundesliga 2'},
    {'nombre': 'SpVgg Greuther Fürth', 'liga': 'Bundesliga 2'},
    {'nombre': 'FC Erzgebirge Aue', 'liga': 'Bundesliga 2'},
    {'nombre': 'VfL Osnabrück', 'liga': 'Bundesliga 2'},
    {'nombre': 'Dynamo Dresden', 'liga': 'Bundesliga 2'},
    {'nombre': 'Eintracht Braunschweig', 'liga': 'Bundesliga 2'},
    {'nombre': 'Karlsruher SC', 'liga': 'Bundesliga 2'},
    {'nombre': 'FC St. Pauli', 'liga': 'Bundesliga 2'},
    {'nombre': 'FC Heidenheim', 'liga': 'Bundesliga 2'},
    {'nombre': 'SSV Jahn Regensburg', 'liga': 'Bundesliga 2'},
    {'nombre': 'Karlsruher SC', 'liga': 'Bundesliga 3'},
    {'nombre': 'VfL Osnabrück', 'liga': 'Bundesliga 3'},
    {'nombre': 'SC Paderborn 07', 'liga': 'Bundesliga 3'},
    {'nombre': 'Hansa Rostock', 'liga': 'Bundesliga 3'},
    {'nombre': 'Holstein Kiel', 'liga': 'Bundesliga 3'},
    {'nombre': 'SG Sonnenhof Großaspach', 'liga': 'Bundesliga 3'},
    {'nombre': 'Chemnitzer FC', 'liga': 'Bundesliga 3'},
    {'nombre': 'VfR Aalen', 'liga': 'Bundesliga 3'},
    {'nombre': 'SpVgg Unterhaching', 'liga': 'Bundesliga 3'},
    {'nombre': 'SV Wehen Wiesbaden', 'liga': 'Bundesliga 3'},
    {'nombre': 'SV Meppen', 'liga': 'Bundesliga 3'},
    {'nombre': 'Würzburger Kickers', 'liga': 'Bundesliga 3'},
    {'nombre': 'Fortuna Köln', 'liga': 'Bundesliga 3'},
    {'nombre': 'Preußen Münster', 'liga': 'Bundesliga 3'},
    {'nombre': 'Rot-Weiß Erfurt', 'liga': 'Bundesliga 3'},
    {'nombre': 'Hallescher FC', 'liga': 'Bundesliga 3'},
    {'nombre': 'Sportfreunde Lotte', 'liga': 'Bundesliga 3'},
    {'nombre': 'SV Meppen', 'liga': 'Bundesliga 3'},
    {'nombre': 'Carl Zeiss Jena', 'liga': 'Bundesliga 3'},
    {'nombre': 'Energie Cottbus', 'liga': 'Bundesliga 3'},
    {'nombre': 'Juventus', 'liga': 'Calcio A'},
    {'nombre': 'Napoli', 'liga': 'Calcio A'},
    {'nombre': 'Roma', 'liga': 'Calcio A'},
    {'nombre': 'Inter Milan', 'liga': 'Calcio A'},
    {'nombre': 'AC Milan', 'liga': 'Calcio A'},
    {'nombre': 'Lazio', 'liga': 'Calcio A'},
    {'nombre': 'Atalanta', 'liga': 'Calcio A'},
    {'nombre': 'Fiorentina', 'liga': 'Calcio A'},
    {'nombre': 'Torino', 'liga': 'Calcio A'},
    {'nombre': 'Sampdoria', 'liga': 'Calcio A'},
    {'nombre': 'Sassuolo', 'liga': 'Calcio A'},
    {'nombre': 'Cagliari', 'liga': 'Calcio A'},
    {'nombre': 'Udinese', 'liga': 'Calcio A'},
    {'nombre': 'Bologna', 'liga': 'Calcio A'},
    {'nombre': 'Chievo Verona', 'liga': 'Calcio A'},
    {'nombre': 'Genoa', 'liga': 'Calcio A'},
    {'nombre': 'Empoli', 'liga': 'Calcio A'},
    {'nombre': 'Crotone', 'liga': 'Calcio A'},
    {'nombre': 'Pescara', 'liga': 'Calcio A'},
    {'nombre': 'Palermo', 'liga': 'Calcio A'},
    {'nombre': 'Benevento', 'liga': 'Calcio A'},
    {'nombre': 'Verona', 'liga': 'Calcio B'},
    {'nombre': 'Frosinone', 'liga': 'Calcio B'},
    {'nombre': 'Bari', 'liga': 'Calcio B'},
    {'nombre': 'Cesena', 'liga': 'Calcio B'},
    {'nombre': 'Salernitana', 'liga': 'Calcio B'},
    {'nombre': 'Spezia', 'liga': 'Calcio B'},
    {'nombre': 'Virtus Entella', 'liga': 'Calcio B'},
    {'nombre': 'Perugia', 'liga': 'Calcio B'},
    {'nombre': 'Ternana', 'liga': 'Calcio B'},
    {'nombre': 'Carpi', 'liga': 'Calcio B'},
    {'nombre': 'Avellino', 'liga': 'Calcio B'},
    {'nombre': 'Novara', 'liga': 'Calcio B'},
    {'nombre': 'Pro Vercelli', 'liga': 'Calcio B'},
    {'nombre': 'Ascoli', 'liga': 'Calcio B'},
    {'nombre': 'Foggia', 'liga': 'Calcio B'},
    {'nombre': 'Cremonese', 'liga': 'Calcio B'},
    {'nombre': 'Empoli', 'liga': 'Calcio B'},
    {'nombre': 'Venezia', 'liga': 'Calcio B'},
    {'nombre': 'Pescara', 'liga': 'Calcio B'},
    {'nombre': 'Palermo', 'liga': 'Calcio B'},
    {'nombre': 'Brescia', 'liga': 'Calcio B'},
    {'nombre': 'Livorno', 'liga': 'Calcio B'},
    {'nombre': 'Atlanta United', 'liga': 'MLS'},
    {'nombre': 'Chicago Fire', 'liga': 'MLS'},
    {'nombre': 'Colorado Rapids', 'liga': 'MLS'},
    {'nombre': 'Columbus Crew SC', 'liga': 'MLS'},
    {'nombre': 'D.C. United', 'liga': 'MLS'},
    {'nombre': 'FC Dallas', 'liga': 'MLS'},
    {'nombre': 'Houston Dynamo', 'liga': 'MLS'},
    {'nombre': 'LA Galaxy', 'liga': 'MLS'},
    {'nombre': 'Los Angeles FC', 'liga': 'MLS'},
    {'nombre': 'Minnesota United FC', 'liga': 'MLS'},
    {'nombre': 'Montreal Impact', 'liga': 'MLS'},
    {'nombre': 'New England Revolution', 'liga': 'MLS'},
    {'nombre': 'New York City FC', 'liga': 'MLS'},
    {'nombre': 'New York Red Bulls', 'liga': 'MLS'},
    {'nombre': 'Orlando City SC', 'liga': 'MLS'},
    {'nombre': 'Philadelphia Union', 'liga': 'MLS'},
    {'nombre': 'Portland Timbers', 'liga': 'MLS'},
    {'nombre': 'Real Salt Lake', 'liga': 'MLS'},
    {'nombre': 'San Jose Earthquakes', 'liga': 'MLS'},
    {'nombre': 'Seattle Sounders FC', 'liga': 'MLS'},
    {'nombre': 'Sporting Kansas City', 'liga': 'MLS'},
    {'nombre': 'Toronto FC', 'liga': 'MLS'},
    {'nombre': 'Vancouver Whitecaps FC', 'liga': 'MLS'},
    {'nombre': 'Brann', 'liga': 'Eliteserien'},
    {'nombre': 'Haugesund', 'liga': 'Eliteserien'},
    {'nombre': 'Kristiansund', 'liga': 'Eliteserien'},
    {'nombre': 'Lillestrøm', 'liga': 'Eliteserien'},
    {'nombre': 'Molde', 'liga': 'Eliteserien'},
    {'nombre': 'Odd', 'liga': 'Eliteserien'},
    {'nombre': 'Rosenborg', 'liga': 'Eliteserien'},
    {'nombre': 'Sandefjord', 'liga': 'Eliteserien'},
    {'nombre': 'Sarpsborg 08', 'liga': 'Eliteserien'},
    {'nombre': 'Sogndal', 'liga': 'Eliteserien'},
    {'nombre': 'Start', 'liga': 'Eliteserien'},
    {'nombre': 'Stabæk', 'liga': 'Eliteserien'},
    {'nombre': 'Strømsgodset', 'liga': 'Eliteserien'},
    {'nombre': 'Tromsø', 'liga': 'Eliteserien'},
    {'nombre': 'Vålerenga', 'liga': 'Eliteserien'},
    {'nombre': 'Aberdeen', 'liga': 'Scottish Prem'},
    {'nombre': 'Celtic', 'liga': 'Scottish Prem'},
    {'nombre': 'Dundee', 'liga': 'Scottish Prem'},
    {'nombre': 'Hamilton Academical', 'liga': 'Scottish Prem'},
    {'nombre': 'Heart of Midlothian', 'liga': 'Scottish Prem'},
    {'nombre': 'Hibernian', 'liga': 'Scottish Prem'},
    {'nombre': 'Kilmarnock', 'liga': 'Scottish Prem'},
    {'nombre': 'Motherwell', 'liga': 'Scottish Prem'},
    {'nombre': 'Partick Thistle', 'liga': 'Scottish Prem'},
    {'nombre': 'Rangers', 'liga': 'Scottish Prem'},
    {'nombre': 'Ross County', 'liga': 'Scottish Prem'},
    {'nombre': 'St. Johnstone', 'liga': 'Scottish Prem'},
    {'nombre': 'Albacete', 'liga': 'Liga 123'},
    {'nombre': 'Alcorcón', 'liga': 'Liga 123'},
    {'nombre': 'Almería', 'liga': 'Liga 123'},
    {'nombre': 'Cádiz', 'liga': 'Liga 123'},
    {'nombre': 'Córdoba', 'liga': 'Liga 123'},
    {'nombre': 'Cultural Leonesa', 'liga': 'Liga 123'},
    {'nombre': 'Getafe', 'liga': 'Liga 123'},
    {'nombre': 'Gimnàstic de Tarragona', 'liga': 'Liga 123'},
    {'nombre': 'Girona', 'liga': 'Liga 123'},
    {'nombre': 'Huesca', 'liga': 'Liga 123'},
    {'nombre': 'Levante', 'liga': 'Liga 123'},
    {'nombre': 'Lugo', 'liga': 'Liga 123'},
    {'nombre': 'Mallorca', 'liga': 'Liga 123'},
    {'nombre': 'Mirandés', 'liga': 'Liga 123'},
    {'nombre': 'Numancia', 'liga': 'Liga 123'},
    {'nombre': 'Osasuna', 'liga': 'Liga 123'},
    {'nombre': 'Oviedo', 'liga': 'Liga 123'},
    {'nombre': 'Rayo Vallecano', 'liga': 'Liga 123'},
    {'nombre': 'Reus Deportiu', 'liga': 'Liga 123'},
    {'nombre': 'Sevilla Atlético', 'liga': 'Liga 123'},
    {'nombre': 'Tenerife', 'liga': 'Liga 123'},
    {'nombre': 'UCAM Murcia', 'liga': 'Liga 123'},
    {'nombre': 'Valladolid', 'liga': 'Liga 123'},
    {'nombre': 'Zaragoza', 'liga': 'Liga 123'},
    {'nombre': 'AIK', 'liga': 'Allsvenskan'},
    {'nombre': 'BK Häcken', 'liga': 'Allsvenskan'},
    {'nombre': 'Djurgårdens IF', 'liga': 'Allsvenskan'},
    {'nombre': 'GIF Sundsvall', 'liga': 'Allsvenskan'},
    {'nombre': 'Hammarby IF', 'liga': 'Allsvenskan'},
    {'nombre': 'Halmstads BK', 'liga': 'Allsvenskan'},
    {'nombre': 'IF Elfsborg', 'liga': 'Allsvenskan'},
    {'nombre': 'IFK Göteborg', 'liga': 'Allsvenskan'},
    {'nombre': 'IFK Norrköping', 'liga': 'Allsvenskan'},
    {'nombre': 'Jönköpings Södra', 'liga': 'Allsvenskan'},
    {'nombre': 'Kalmar FF', 'liga': 'Allsvenskan'},
    {'nombre': 'Malmö FF', 'liga': 'Allsvenskan'},
    {'nombre': 'Örebro SK', 'liga': 'Allsvenskan'},
    {'nombre': 'Östersunds FK', 'liga': 'Allsvenskan'},
    {'nombre': 'Sirius', 'liga': 'Allsvenskan'},
    {'nombre': 'Bohemian FC', 'liga': 'SSE Airtricity'},
    {'nombre': 'Bray Wanderers', 'liga': 'SSE Airtricity'},
    {'nombre': 'Cork City FC', 'liga': 'SSE Airtricity'},
    {'nombre': 'Derry City FC', 'liga': 'SSE Airtricity'},
    {'nombre': 'Drogheda United', 'liga': 'SSE Airtricity'},
    {'nombre': 'Dundalk FC', 'liga': 'SSE Airtricity'},
    {'nombre': 'Finn Harps', 'liga': 'SSE Airtricity'},
    {'nombre': 'Galway United', 'liga': 'SSE Airtricity'},
    {'nombre': 'Limerick FC', 'liga': 'SSE Airtricity'},
    {'nombre': 'Shamrock Rovers', 'liga': 'SSE Airtricity'},
    {'nombre': 'Sligo Rovers', 'liga': 'SSE Airtricity'},
    {'nombre': 'St. Patrick\'s Athletic', 'liga': 'SSE Airtricity'},
    {'nombre': 'Waterford FC', 'liga': 'SSE Airtricity'},
    {'nombre': 'Wexford FC', 'liga': 'SSE Airtricity'},
    {'nombre': 'Arka Gdynia', 'liga': 'Ekstraklasa'},
    {'nombre': 'Bruk-Bet Termalica Nieciecza', 'liga': 'Ekstraklasa'},
    {'nombre': 'Cracovia', 'liga': 'Ekstraklasa'},
    {'nombre': 'Górnik Zabrze', 'liga': 'Ekstraklasa'},
    {'nombre': 'Jagiellonia Białystok', 'liga': 'Ekstraklasa'},
    {'nombre': 'Korona Kielce', 'liga': 'Ekstraklasa'},
    {'nombre': 'Lech Poznań', 'liga': 'Ekstraklasa'},
    {'nombre': 'Lechia Gdańsk', 'liga': 'Ekstraklasa'},
    {'nombre': 'Legia Warszawa', 'liga': 'Ekstraklasa'},
    {'nombre': 'Piast Gliwice', 'liga': 'Ekstraklasa'},
    {'nombre': 'Pogoń Szczecin', 'liga': 'Ekstraklasa'},
    {'nombre': 'Sandecja Nowy Sącz', 'liga': 'Ekstraklasa'},
    {'nombre': 'Wisła Kraków', 'liga': 'Ekstraklasa'},
    {'nombre': 'Wisła Płock', 'liga': 'Ekstraklasa'},
    {'nombre': 'Zagłębie Lubin', 'liga': 'Ekstraklasa'},
    {'nombre': 'Akmat Grozny', 'liga': 'Russian League'},
    {'nombre': 'Amkar Perm', 'liga': 'Russian League'},
    {'nombre': 'Anzhi Makhachkala', 'liga': 'Russian League'},
    {'nombre': 'Arsenal Tula', 'liga': 'Russian League'},
    {'nombre': 'CSKA Moscow', 'liga': 'Russian League'},
    {'nombre': 'Dynamo Moscow', 'liga': 'Russian League'},
    {'nombre': 'Krasnodar', 'liga': 'Russian League'},
    {'nombre': 'Lokomotiv Moscow', 'liga': 'Russian League'},
    {'nombre': 'Rostov', 'liga': 'Russian League'},
    {'nombre': 'Rubin Kazan', 'liga': 'Russian League'},
    {'nombre': 'SKA-Khabarovsk', 'liga': 'Russian League'},
    {'nombre': 'Spartak Moscow', 'liga': 'Russian League'},
    {'nombre': 'Tosno', 'liga': 'Russian League'},
    {'nombre': 'Ufa', 'liga': 'Russian League'},
    {'nombre': 'Ural', 'liga': 'Russian League'},
    {'nombre': 'Zenit St. Petersburg', 'liga': 'Russian League'},
    {'nombre': 'Alanyaspor', 'liga': 'Süper Lig'},
    {'nombre': 'Antalyaspor', 'liga': 'Süper Lig'},
    {'nombre': 'Basaksehir', 'liga': 'Süper Lig'},
    {'nombre': 'Besiktas', 'liga': 'Süper Lig'},
    {'nombre': 'Bursaspor', 'liga': 'Süper Lig'},
    {'nombre': 'Fenerbahce', 'liga': 'Süper Lig'},
    {'nombre': 'Genclerbirligi', 'liga': 'Süper Lig'},
    {'nombre': 'Goztepe', 'liga': 'Süper Lig'},
    {'nombre': 'Istanbulspor', 'liga': 'Süper Lig'},
    {'nombre': 'Karabukspor', 'liga': 'Süper Lig'},
    {'nombre': 'Kasimpasa', 'liga': 'Süper Lig'},
    {'nombre': 'Kayserispor', 'liga': 'Süper Lig'},
    {'nombre': 'Konyaspor', 'liga': 'Süper Lig'},
    {'nombre': 'Osmanlispor', 'liga': 'Süper Lig'},
    {'nombre': 'Sivasspor', 'liga': 'Süper Lig'},
    {'nombre': 'Trabzonspor', 'liga': 'Süper Lig'},
    {'nombre': 'Yeni Malatyaspor', 'liga': 'Süper Lig'},
    {'nombre': 'FC Wacker Innsbruck', 'liga': 'O Bundesliga'},
    {'nombre': 'SKN St. Pölten', 'liga': 'O Bundesliga'},
    {'nombre': 'SCR Altach', 'liga': 'O Bundesliga'},
    {'nombre': 'LASK Linz', 'liga': 'O Bundesliga'},
    {'nombre': 'Wolfsberger AC', 'liga': 'O Bundesliga'},
    {'nombre': 'Admira Wacker Mödling', 'liga': 'O Bundesliga'},
    {'nombre': 'Rapid Wien', 'liga': 'O Bundesliga'},
    {'nombre': 'Red Bull Salzburg', 'liga': 'O Bundesliga'},
    {'nombre': 'Jeonbuk Hyundai Motors', 'liga': 'Liga Koreana'},
    {'nombre': 'Jeju United', 'liga': 'Liga Koreana'},
    {'nombre': 'Suwon Samsung Bluewings', 'liga': 'Liga Koreana'},
    {'nombre': 'FC Seoul', 'liga': 'Liga Koreana'},
    {'nombre': 'Ulsan Hyundai', 'liga': 'Liga Koreana'},
    {'nombre': 'Pohang Steelers', 'liga': 'Liga Koreana'},
    {'nombre': 'Sangju Sangmu', 'liga': 'Liga Koreana'},
    {'nombre': 'Gangwon FC', 'liga': 'Liga Koreana'},
    {'nombre': 'Daegu FC', 'liga': 'Liga Koreana'},
    {'nombre': 'Incheon United', 'liga': 'Liga Koreana'},
    {'nombre': 'Gwangju FC', 'liga': 'Liga Koreana'},
    {'nombre': 'Jeonnam Dragons', 'liga': 'Liga Koreana'},
    {'nombre': 'Benfica', 'liga': 'Liga NOS'},
    {'nombre': 'Porto', 'liga': 'Liga NOS'},
    {'nombre': 'Sporting CP', 'liga': 'Liga NOS'},
    {'nombre': 'Braga', 'liga': 'Liga NOS'},
    {'nombre': 'Vitória Guimarães', 'liga': 'Liga NOS'},
    {'nombre': 'Rio Ave', 'liga': 'Liga NOS'},
    {'nombre': 'Marítimo', 'liga': 'Liga NOS'},
    {'nombre': 'Boavista', 'liga': 'Liga NOS'},
    {'nombre': 'Chaves', 'liga': 'Liga NOS'},
    {'nombre': 'Belenenses', 'liga': 'Liga NOS'},
    {'nombre': 'P. Ferreira', 'liga': 'Liga NOS'},
    {'nombre': 'Estoril', 'liga': 'Liga NOS'},
    {'nombre': 'Feirense', 'liga': 'Liga NOS'},
    {'nombre': 'Moreirense', 'liga': 'Liga NOS'},
    {'nombre': 'Aves', 'liga': 'Liga NOS'},
    {'nombre': 'Tondela', 'liga': 'Liga NOS'},
    {'nombre': 'Vitória Setúbal', 'liga': 'Liga NOS'},
    {'nombre': 'Gil Vicente', 'liga': 'Liga NOS'},
    {'nombre': 'Colo-Colo', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'Universidad de Chile', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'Universidad Católica', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'Deportes Iquique', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'Palestino', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'Deportes Temuco', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'Unión Española', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'Huachipato', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'Audax Italiano', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'OHiggins', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'Everton', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'Santiago Wanderers', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'Curicó Unido', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'San Luis de Quillota', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'Antofagasta', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'Deportes Temuco', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'Deportes Antofagasta', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'Unión La Calera', 'liga': 'Campeonato Scotiabank'},
    {'nombre': 'Atlético Nacional', 'liga': 'Liga Dimayor'},
    {'nombre': 'Deportivo Cali', 'liga': 'Liga Dimayor'},
    {'nombre': 'Millonarios', 'liga': 'Liga Dimayor'},
    {'nombre': 'Junior', 'liga': 'Liga Dimayor'},
    {'nombre': 'Independiente Medellín', 'liga': 'Liga Dimayor'},
    {'nombre': 'Santa Fe', 'liga': 'Liga Dimayor'},
    {'nombre': 'Once Caldas', 'liga': 'Liga Dimayor'},
    {'nombre': 'América de Cali', 'liga': 'Liga Dimayor'},
    {'nombre': 'Deportes Tolima', 'liga': 'Liga Dimayor'},
    {'nombre': 'Alianza Petrolera', 'liga': 'Liga Dimayor'},
    {'nombre': 'Atlético Bucaramanga', 'liga': 'Liga Dimayor'},
    {'nombre': 'La Equidad', 'liga': 'Liga Dimayor'},
    {'nombre': 'Patriotas Boyacá', 'liga': 'Liga Dimayor'},
    {'nombre': 'Rionegro Águilas', 'liga': 'Liga Dimayor'},
    {'nombre': 'Tigres F.C.', 'liga': 'Liga Dimayor'},
    {'nombre': 'Cortuluá', 'liga': 'Liga Dimayor'},
    {'nombre': 'Jaguares de Córdoba', 'liga': 'Liga Dimayor'},
    {'nombre': 'Envigado', 'liga': 'Liga Dimayor'},
    {'nombre': 'Deportivo Pasto', 'liga': 'Liga Dimayor'},
    {'nombre': 'Atlético Huila', 'liga': 'Liga Dimayor'},
    {'nombre': 'Rionegro Águilas', 'liga': 'Liga Dimayor'},
    {'nombre': 'Boyacá Chicó', 'liga': 'Liga Dimayor'},
    {'nombre': 'Alianza Petrolera', 'liga': 'Liga Dimayor'},
    {'nombre': 'Tigres F.C.', 'liga': 'Liga Dimayor'},
    {'nombre': 'Deportes Quindío', 'liga': 'Liga Dimayor'},
    {'nombre': 'Universitario Popayán', 'liga': 'Liga Dimayor'},
    {'nombre': 'Club América', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Chivas de Guadalajara', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Tigres UANL', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Monterrey', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Pumas UNAM', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Cruz Azul', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Toluca', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Santos Laguna', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Querétaro', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Pachuca', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Atlas', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Xolos de Tijuana', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Necaxa', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'León', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Veracruz', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Puebla', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Morelia', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Lobos BUAP', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Cafetaleros de Tapachula', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Juárez FC', 'liga': 'Liga Bancomer MX'},
    {'nombre': 'Kashima Antlers', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Kawasaki Frontale', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Yokohama F. Marinos', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'FC Tokyo', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Urawa Red Diamonds', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Sagan Tosu', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Sanfrecce Hiroshima', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Vissel Kobe', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Omiya Ardija', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Albirex Niigata', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Shonan Bellmare', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Kashiwa Reysol', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Vegalta Sendai', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Gamba Osaka', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Shimizu S-Pulse', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Consadole Sapporo', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Ventforet Kofu', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Júbilo Iwata', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Avispa Fukuoka', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Tokushima Vortis', 'liga': 'Meiji Yasuda J1'},
    {'nombre': 'Al Ahli', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Hilal', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Nassr', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Ittihad', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Shabab', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Ahli Jeddah', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Batin', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Taawon', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Faisaly', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Ettifaq', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Raed', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Fateh', 'liga': 'Daery Jameel'},
    {'nombre': 'Ohod', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Quadisiya', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Hazm', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Wehda', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Khaleej', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Ittifaq Dammam', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Wehda FC', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Fayha', 'liga': 'Daery Jameel'},
    {'nombre': 'Al Nojoom', 'liga': 'Daery Jameel'},
    {'nombre': 'Adelaide United', 'liga': 'Hyundai A-League'},
    {'nombre': 'Brisbane Roar', 'liga': 'Hyundai A-League'},
    {'nombre': 'Central Coast Mariners', 'liga': 'Hyundai A-League'},
    {'nombre': 'Melbourne City', 'liga': 'Hyundai A-League'},
    {'nombre': 'Melbourne Victory', 'liga': 'Hyundai A-League'},
    {'nombre': 'Newcastle Jets', 'liga': 'Hyundai A-League'},
    {'nombre': 'Perth Glory', 'liga': 'Hyundai A-League'},
    {'nombre': 'Sydney FC', 'liga': 'Hyundai A-League'},
    {'nombre': 'Wellington Phoenix', 'liga': 'Hyundai A-League'},
    {'nombre': 'Western Sydney Wanderers', 'liga': 'Hyundai A-League'},
    {'nombre': 'Boca Juniors', 'liga': 'Primera División Argentina'},
    {'nombre': 'River Plate', 'liga': 'Primera División Argentina'},
    {'nombre': 'Independiente', 'liga': 'Primera División Argentina'},
    {'nombre': 'Racing Club', 'liga': 'Primera División Argentina'},
    {'nombre': 'San Lorenzo', 'liga': 'Primera División Argentina'},
    {'nombre': 'Huracán', 'liga': 'Primera División Argentina'},
    {'nombre': 'Estudiantes', 'liga': 'Primera División Argentina'},
    {'nombre': 'Gimnasia y Esgrima La Plata', 'liga': 'Primera División Argentina'},
    {'nombre': 'Vélez Sarsfield', 'liga': 'Primera División Argentina'},
    {'nombre': 'Lanús', 'liga': 'Primera División Argentina'},
    {'nombre': 'Banfield', 'liga': 'Primera División Argentina'},
    {'nombre': 'Argentinos Juniors', 'liga': 'Primera División Argentina'},
    {'nombre': 'Rosario Central', 'liga': 'Primera División Argentina'},
    {'nombre': 'Newells Old Boys', 'liga': 'Primera División Argentina'},
    {'nombre': 'Talleres', 'liga': 'Primera División Argentina'},
    {'nombre': 'Belgrano', 'liga': 'Primera División Argentina'},
    {'nombre': 'Godoy Cruz', 'liga': 'Primera División Argentina'},
    {'nombre': 'Atlético Tucumán', 'liga': 'Primera División Argentina'},
    {'nombre': 'Colón', 'liga': 'Primera División Argentina'},
    {'nombre': 'Unión', 'liga': 'Primera División Argentina'},
    {'nombre': 'San Martín de San Juan', 'liga': 'Primera División Argentina'},
    {'nombre': 'Patronato', 'liga': 'Primera División Argentina'},
    {'nombre': 'Temperley', 'liga': 'Primera División Argentina'},
    {'nombre': 'Chacarita Juniors', 'liga': 'Primera División Argentina'},
    {'nombre': 'Arsenal', 'liga': 'Primera División Argentina'},
    {'nombre': 'Olimpo', 'liga': 'Primera División Argentina'},
    {'nombre': 'Defensa y Justicia', 'liga': 'Primera División Argentina'},
    {'nombre': 'Tigre', 'liga': 'Primera División Argentina'},
    {'nombre': 'Atlético Rafaela', 'liga': 'Primera División Argentina'},
    {'nombre': 'Quilmes', 'liga': 'Primera División Argentina'},
    {'nombre': 'Sarmiento', 'liga': 'Primera División Argentina'},
]

paises = [
    {"nombre": "Alemania", "bandera": "alemania.png"},
    {"nombre": "Argentina", "bandera": "argentina.png"},
    {"nombre": "Arabia Saudita", "bandera": "arabia_saudita.png"},
    {"nombre": "Argelia", "bandera": "argelia.png"},
    {"nombre": "Australia", "bandera": "australia.png"},
    {"nombre": "Austria", "bandera": "austria.png"},
    {"nombre": "Bélgica", "bandera": "belgica.png"},
    {"nombre": "Bolivia", "bandera": "bolivia.png"},
    {"nombre": "Brasil", "bandera": "brasil.png"},
    {"nombre": "Canadá", "bandera": "canada.png"},
    {"nombre": "Camerún", "bandera": "camerun.png"},
    {"nombre": "Chile", "bandera": "chile.png"},
    {"nombre": "China", "bandera": "china.png"},
    {"nombre": "Colombia", "bandera": "colombia.png"},
    {"nombre": "Corea del Sur", "bandera": "corea_del_sur.png"},
    {"nombre": "Costa de Marfil", "bandera": "costa_de_marfil.png"},
    {"nombre": "Croacia", "bandera": "croacia.png"},
    {"nombre": "Ecuador", "bandera": "ecuador.png"},
    {"nombre": "Egipto", "bandera": "egipto.png"},
    {"nombre": "Escocia", "bandera": "escocia.png"},
    {"nombre": "Eslovaquia", "bandera": "eslovaquia.png"},
    {"nombre": "Eslovenia", "bandera": "eslovenia.png"},
    {"nombre": "España", "bandera": "espana.png"},
    {"nombre": "Estados Unidos", "bandera": "estados_unidos.png"},
    {"nombre": "Finlandia", "bandera": "finlandia.png"},
    {"nombre": "Francia", "bandera": "francia.png"},
    {"nombre": "Ghana", "bandera": "ghana.png"},
    {"nombre": "Grecia", "bandera": "grecia.png"},
    {"nombre": "Holanda", "bandera": "holanda.png"},
    {"nombre": "Inglaterra", "bandera": "inglaterra.png"},
    {"nombre": "Irlanda", "bandera": "irlanda.png"},
    {"nombre": "Irlanda del Norte", "bandera": "irlanda_del_norte.png"},
    {"nombre": "Italia", "bandera": "italia.png"},
    {"nombre": "Japón", "bandera": "japon.png"},
    {"nombre": "Marruecos", "bandera": "marruecos.png"},
    {"nombre": "México", "bandera": "mexico.png"},
    {"nombre": "Nigeria", "bandera": "nigeria.png"},
    {"nombre": "Noruega", "bandera": "noruega.png"},
    {"nombre": "Nueva Zelanda", "bandera": "nueva_zelanda.png"},
    {"nombre": "Paraguay", "bandera": "paraguay.png"},
    {"nombre": "Perú", "bandera": "peru.png"},
    {"nombre": "Polonia", "bandera": "polonia.png"},
    {"nombre": "Portugal", "bandera": "portugal.png"},
    {"nombre": "República Checa", "bandera": "republica_checa.png"},
    {"nombre": "Rumania", "bandera": "rumania.png"},
    {"nombre": "Rusia", "bandera": "rusia.png"},
    {"nombre": "Serbia", "bandera": "serbia.png"},
    {"nombre": "Sudafrica", "bandera": "sudafrica.png"},
    {"nombre": "Suecia", "bandera": "suecia.png"},
    {"nombre": "Suiza", "bandera": "suiza.png"},
    {"nombre": "Turquía", "bandera": "turquia.png"},
    {"nombre": "Uruguay", "bandera": "uruguay.png"},
    {"nombre": "Venezuela", "bandera": "venezuela.png"}
]


def rellenar_equipos():
    if not Equipo.objects.all().exists():
        for equipo_data in equipos_fifa18:
            equipo = Equipo.objects.create(nombre=equipo_data['nombre'], liga=equipo_data['liga'])
            equipo.save()
            
def rellenar_paises():
    if not Nacionalidad.objects.all().exists():
        for pais in paises:
            n = Nacionalidad(pais=pais['nombre'], bandera=pais['bandera'])
            n.save()
            
